In [ ]:
import pandas as pd
from pathlib import Path

base = Path('output-parallel')
dfs = []

for path in base.glob("features_count_*.out"):
    dfs.append(pd.read_csv(path))

result = pd.concat(dfs, ignore_index=True)

In [13]:
result

              state      county parks pitches sports_centres schools
0          Nebraska    Cheyenne    12      16              0      30
1          Nebraska     Madison    26      75              1      97
2          Nebraska   Box_Butte    16      21              0      57
3          Nebraska      Harlan     5       3              0       4
4          Nebraska       Keith    16      18              2      32
...             ...         ...   ...     ...            ...     ...
2752  New Hampshire    Sullivan    24     117              5      59
2753  New Hampshire     Belknap    36     173              3      55
2754  New Hampshire  Rockingham    98     788             47     218
2755  New Hampshire     Carroll    25     288              7      67
2756  New Hampshire    Cheshire    42     113              5      82

[2757 rows x 6 columns]

In [ ]:
result.to_csv(base / "features_count_2025-04-09.csv", index=False)

 features_count_Alabama.out                 features_count_Nebraska.out
 features_count_Arizona.out                 features_count_Nevada.out
 features_count_Arkansas.out               'features_count_New Hampshire.out'
 features_count_California.out             'features_count_New Jersey.out'
 features_count_Colorado.out               'features_count_New Mexico.out'
 features_count_Connecticut.out            'features_count_New York.out'
 features_count_Delaware.out               'features_count_North Carolina.out'
'features_count_District of Columbia.out'  'features_count_North Dakota.out'
 features_count_Florida.out                 features_count_Ohio.out
 features_count_Georgia.out                 features_count_Oklahoma.out
 features_count_Idaho.out                   features_count_Oregon.out
 features_count_Illinois.out                features_count_Pennsylvania.out
 features_count_Indiana.out                'features_count_Puerto Rico.out'
 features_count_Iowa.out                   'features_count_Rhode Island.out'
 features_count_Kansas.out                 'features_count_South Carolina.out'
 features_count_Kentucky.out               'features_count_South Dakota.out'
 features_count_Louisiana.out               features_count_Tennessee.out
 features_count_Maine.out                   features_count_Texas.out
 features_count_Maryland.out                features_count_Utah.out
 features_count_Massachusetts.out           features_count_Vermont.out
 features_count_Michigan.out                features_count_Virginia.out
 features_count_Minnesota.out               features_count_Washington.out
 features_count_Mississippi.out            'features_count_West Virginia.out'
 features_count_Missouri.out                features_count_Wisconsin.out
 features_count_Montana.out                 features_count_Wyoming.out

In [7]:
[f.name for f in base.iterdir()]

FileNotFoundError: [Errno 2] No such file or directory: '~/osm_project/dev/count_features/output-parallel'